---
title: "10kmutants_library_analysis"
author: "Haider Inam"
date: "2/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# knitr::opts_knit$set(root.dir = normalizePath(".."))
```

```{r,include=F}
# rm(list=ls())
library(knitr)
library(tictoc)
library(workflowr)
library(VennDiagram)
library(dplyr)
library(foreach)
library(doParallel)
library(ggplot2)
library(reshape2)
library(RColorBrewer)
library(devtools)
library(ggsignif)
library(plotly)
library(BiocManager)
library(drc)
# library(ensembldb) #Loading this with Dplyr commands seems to throw an error in Rmd
# library(EnsDb.Hsapiens.v86) #Loading this with Dplyr commands seems to throw an error in Rmd

######################Cleanup for GGPlot2#########################################
cleanup=theme_bw() +
  theme(plot.title = element_text(hjust=.5),
        panel.grid.major = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(color = "black"),
        axis.text = element_text(face="bold",color="black",size="11"),
        text=element_text(size=11,face="bold"),
        axis.title=element_text(face="bold",size="11"))
```

```{r}

d0=read.table("data/Consensus_Data/Novogene_lane2/10kmutants_inhouse/sp2_d0.1.consensus.variant-calls.mut",header=T,stringsAsFactors = F,sep="\t")
d2=read.csv("data/Consensus_Data/Novogene_lane2/10kmutants_inhouse/sp2_d2_300.1.consensus.variant-calls.mut",header=T,stringsAsFactors = F,sep="\t")
d4=read.csv("data/Consensus_Data/Novogene_lane2/10kmutants_inhouse/sp2_d4_300.1.consensus.variant-calls.mut",header=T,stringsAsFactors = F,sep="\t")

d0=d0%>%filter(!alt%in%"<DEL>",alt_depth<=2000,variation_type%in%"snv")
d2=d2%>%filter(!alt%in%"<DEL>",alt_depth<=2000,variation_type%in%"snv")
d4=d4%>%filter(!alt%in%"<DEL>",alt_depth<=2000,variation_type%in%"snv")




d0=d0%>%
  mutate(ALT=alt,End=end,mutant=case_when(End==130872896 & ALT=="T" ~ "T315I",
                          End==130862970 & ALT=="C" ~ "Y253H",
                          End==130862977 & ALT=="T" ~ "E255V",
                          End==130873004 & ALT=="C" ~ "M351T",
                          End==130862962 & ALT=="A" ~ "G250E",
                          End==130874969 & ALT=="C" ~ "H396P",
                          End==130862955 & ALT=="G" ~ "L248V",
                          End==130874969 & ALT=="G" ~ "H396R",
                          End==130862971 & ALT=="T" ~ "Y253F",
                          End==130862969 & ALT=="T" ~ "Q252H",
                          End==130862976 & ALT=="A" ~ "E255K",
                          End==130872901 & ALT=="C" ~ "F317L",
                          End==130873027 & ALT=="C" ~ "F359L",
                          End==130873027 & ALT=="G" ~ "F359V",
                          End==130873027 & ALT=="A" ~ "F359I",
                          End==130873016 & ALT=="G" ~ "E355G",
                          End==130873016 & ALT=="C" ~ "E355A",
                          End==130878519 & ALT=="A" ~ "E459K",
                          End==130872911 & ALT=="G" ~ "Y320C",
                          End==130872133 & ALT=="G" ~ "D276G",
                          End==130862969 & ALT=="C" ~ "Q252Hsyn", ###The mutants below were found only in the ENU mutagenized pools
                          End==130872885 & ALT=="G" ~ "F311L",
                          End==130873028 & ALT=="G" ~ "F359C",
                          End==130874971 & ALT=="C" ~ "A397P",
                          End==130862854 & ALT=="G" ~ "H214R",
                          End==130872146 & ALT=="C" ~ "V280syn",
                          End==130872161 & ALT=="T" ~ "K285N",
                          End==130872923 & ALT=="G" ~ "L324R",
                          End==130872983 & ALT=="T" ~ "A344D",
                          End==130872145 & ALT=="A" ~ "V280E",
                          End==130872200 & ALT=="A" ~ "L298Lsyn",
                          End==130874932 & ALT=="A" ~ "L384M",
                          End==130880101 & ALT=="C" ~ "F486S",
                          End==130880502 & ALT=="A" ~ "V506M",
                          End==130872171 & ALT=="A" ~ "V289I"))
d2=d2%>%
  mutate(ALT=alt,End=end,mutant=case_when(End==130872896 & ALT=="T" ~ "T315I",
                          End==130862970 & ALT=="C" ~ "Y253H",
                          End==130862977 & ALT=="T" ~ "E255V",
                          End==130873004 & ALT=="C" ~ "M351T",
                          End==130862962 & ALT=="A" ~ "G250E",
                          End==130874969 & ALT=="C" ~ "H396P",
                          End==130862955 & ALT=="G" ~ "L248V",
                          End==130874969 & ALT=="G" ~ "H396R",
                          End==130862971 & ALT=="T" ~ "Y253F",
                          End==130862969 & ALT=="T" ~ "Q252H",
                          End==130862976 & ALT=="A" ~ "E255K",
                          End==130872901 & ALT=="C" ~ "F317L",
                          End==130873027 & ALT=="C" ~ "F359L",
                          End==130873027 & ALT=="G" ~ "F359V",
                          End==130873027 & ALT=="A" ~ "F359I",
                          End==130873016 & ALT=="G" ~ "E355G",
                          End==130873016 & ALT=="C" ~ "E355A",
                          End==130878519 & ALT=="A" ~ "E459K",
                          End==130872911 & ALT=="G" ~ "Y320C",
                          End==130872133 & ALT=="G" ~ "D276G",
                          End==130862969 & ALT=="C" ~ "Q252Hsyn", ###The mutants below were found only in the ENU mutagenized pools
                          End==130872885 & ALT=="G" ~ "F311L",
                          End==130873028 & ALT=="G" ~ "F359C",
                          End==130874971 & ALT=="C" ~ "A397P",
                          End==130862854 & ALT=="G" ~ "H214R",
                          End==130872146 & ALT=="C" ~ "V280syn",
                          End==130872161 & ALT=="T" ~ "K285N",
                          End==130872923 & ALT=="G" ~ "L324R",
                          End==130872983 & ALT=="T" ~ "A344D",
                          End==130872145 & ALT=="A" ~ "V280E",
                          End==130872200 & ALT=="A" ~ "L298Lsyn",
                          End==130874932 & ALT=="A" ~ "L384M",
                          End==130880101 & ALT=="C" ~ "F486S",
                          End==130880502 & ALT=="A" ~ "V506M",
                          End==130872171 & ALT=="A" ~ "V289I"))
d4=d4%>%
  mutate(ALT=alt,End=end,mutant=case_when(End==130872896 & ALT=="T" ~ "T315I",
                          End==130862970 & ALT=="C" ~ "Y253H",
                          End==130862977 & ALT=="T" ~ "E255V",
                          End==130873004 & ALT=="C" ~ "M351T",
                          End==130862962 & ALT=="A" ~ "G250E",
                          End==130874969 & ALT=="C" ~ "H396P",
                          End==130862955 & ALT=="G" ~ "L248V",
                          End==130874969 & ALT=="G" ~ "H396R",
                          End==130862971 & ALT=="T" ~ "Y253F",
                          End==130862969 & ALT=="T" ~ "Q252H",
                          End==130862976 & ALT=="A" ~ "E255K",
                          End==130872901 & ALT=="C" ~ "F317L",
                          End==130873027 & ALT=="C" ~ "F359L",
                          End==130873027 & ALT=="G" ~ "F359V",
                          End==130873027 & ALT=="A" ~ "F359I",
                          End==130873016 & ALT=="G" ~ "E355G",
                          End==130873016 & ALT=="C" ~ "E355A",
                          End==130878519 & ALT=="A" ~ "E459K",
                          End==130872911 & ALT=="G" ~ "Y320C",
                          End==130872133 & ALT=="G" ~ "D276G",
                          End==130862969 & ALT=="C" ~ "Q252Hsyn", ###The mutants below were found only in the ENU mutagenized pools
                          End==130872885 & ALT=="G" ~ "F311L",
                          End==130873028 & ALT=="G" ~ "F359C",
                          End==130874971 & ALT=="C" ~ "A397P",
                          End==130862854 & ALT=="G" ~ "H214R",
                          End==130872146 & ALT=="C" ~ "V280syn",
                          End==130872161 & ALT=="T" ~ "K285N",
                          End==130872923 & ALT=="G" ~ "L324R",
                          End==130872983 & ALT=="T" ~ "A344D",
                          End==130872145 & ALT=="A" ~ "V280E",
                          End==130872200 & ALT=="A" ~ "L298Lsyn",
                          End==130874932 & ALT=="A" ~ "L384M",
                          End==130880101 & ALT=="C" ~ "F486S",
                          End==130880502 & ALT=="A" ~ "V506M",
                          End==130872171 & ALT=="A" ~ "V289I"))

d0$time="D0"
d2$time="D2"
d4$time="D4"
alldays=rbind(d0,d2,d4)
ggplot(alldays,aes(x=time,y=alt_depth/depth))+geom_point(color="black",shape=21,size=3,aes(fill=mutant))+facet_wrap(~mutant)+cleanup+scale_y_continuous(trans = "log10",name="MAF")

ggplot(d0,aes(x=mutant,y=alt_depth/depth))+geom_col()+scale_y_continuous(name="MAF")
```

```{r}

d0=read.table("data/Consensus_Data/Novogene_lane2/10kmutants_inhouse/sp2_d0.1.consensus.variant-calls.mut",header=T,stringsAsFactors = F,sep="\t")
d2=read.csv("data/Consensus_Data/Novogene_lane2/10kmutants_inhouse/sp2_d2_600.1.consensus.variant-calls.mut",header=T,stringsAsFactors = F,sep="\t")
d4=read.csv("data/Consensus_Data/Novogene_lane2/10kmutants_inhouse/sp2_d4_600.1.consensus.variant-calls.mut",header=T,stringsAsFactors = F,sep="\t")

d0=d0%>%filter(!alt%in%"<DEL>",alt_depth<=2000,variation_type%in%"snv")
d2=d2%>%filter(!alt%in%"<DEL>",alt_depth<=2000,variation_type%in%"snv")
d4=d4%>%filter(!alt%in%"<DEL>",alt_depth<=2000,variation_type%in%"snv")




d0=d0%>%
  mutate(ALT=alt,End=end,mutant=case_when(End==130872896 & ALT=="T" ~ "T315I",
                          End==130862970 & ALT=="C" ~ "Y253H",
                          End==130862977 & ALT=="T" ~ "E255V",
                          End==130873004 & ALT=="C" ~ "M351T",
                          End==130862962 & ALT=="A" ~ "G250E",
                          End==130874969 & ALT=="C" ~ "H396P",
                          End==130862955 & ALT=="G" ~ "L248V",
                          End==130874969 & ALT=="G" ~ "H396R",
                          End==130862971 & ALT=="T" ~ "Y253F",
                          End==130862969 & ALT=="T" ~ "Q252H",
                          End==130862976 & ALT=="A" ~ "E255K",
                          End==130872901 & ALT=="C" ~ "F317L",
                          End==130873027 & ALT=="C" ~ "F359L",
                          End==130873027 & ALT=="G" ~ "F359V",
                          End==130873027 & ALT=="A" ~ "F359I",
                          End==130873016 & ALT=="G" ~ "E355G",
                          End==130873016 & ALT=="C" ~ "E355A",
                          End==130878519 & ALT=="A" ~ "E459K",
                          End==130872911 & ALT=="G" ~ "Y320C",
                          End==130872133 & ALT=="G" ~ "D276G",
                          End==130862969 & ALT=="C" ~ "Q252Hsyn", ###The mutants below were found only in the ENU mutagenized pools
                          End==130872885 & ALT=="G" ~ "F311L",
                          End==130873028 & ALT=="G" ~ "F359C",
                          End==130874971 & ALT=="C" ~ "A397P",
                          End==130862854 & ALT=="G" ~ "H214R",
                          End==130872146 & ALT=="C" ~ "V280syn",
                          End==130872161 & ALT=="T" ~ "K285N",
                          End==130872923 & ALT=="G" ~ "L324R",
                          End==130872983 & ALT=="T" ~ "A344D",
                          End==130872145 & ALT=="A" ~ "V280E",
                          End==130872200 & ALT=="A" ~ "L298Lsyn",
                          End==130874932 & ALT=="A" ~ "L384M",
                          End==130880101 & ALT=="C" ~ "F486S",
                          End==130880502 & ALT=="A" ~ "V506M",
                          End==130872171 & ALT=="A" ~ "V289I"))
d2=d2%>%
  mutate(ALT=alt,End=end,mutant=case_when(End==130872896 & ALT=="T" ~ "T315I",
                          End==130862970 & ALT=="C" ~ "Y253H",
                          End==130862977 & ALT=="T" ~ "E255V",
                          End==130873004 & ALT=="C" ~ "M351T",
                          End==130862962 & ALT=="A" ~ "G250E",
                          End==130874969 & ALT=="C" ~ "H396P",
                          End==130862955 & ALT=="G" ~ "L248V",
                          End==130874969 & ALT=="G" ~ "H396R",
                          End==130862971 & ALT=="T" ~ "Y253F",
                          End==130862969 & ALT=="T" ~ "Q252H",
                          End==130862976 & ALT=="A" ~ "E255K",
                          End==130872901 & ALT=="C" ~ "F317L",
                          End==130873027 & ALT=="C" ~ "F359L",
                          End==130873027 & ALT=="G" ~ "F359V",
                          End==130873027 & ALT=="A" ~ "F359I",
                          End==130873016 & ALT=="G" ~ "E355G",
                          End==130873016 & ALT=="C" ~ "E355A",
                          End==130878519 & ALT=="A" ~ "E459K",
                          End==130872911 & ALT=="G" ~ "Y320C",
                          End==130872133 & ALT=="G" ~ "D276G",
                          End==130862969 & ALT=="C" ~ "Q252Hsyn", ###The mutants below were found only in the ENU mutagenized pools
                          End==130872885 & ALT=="G" ~ "F311L",
                          End==130873028 & ALT=="G" ~ "F359C",
                          End==130874971 & ALT=="C" ~ "A397P",
                          End==130862854 & ALT=="G" ~ "H214R",
                          End==130872146 & ALT=="C" ~ "V280syn",
                          End==130872161 & ALT=="T" ~ "K285N",
                          End==130872923 & ALT=="G" ~ "L324R",
                          End==130872983 & ALT=="T" ~ "A344D",
                          End==130872145 & ALT=="A" ~ "V280E",
                          End==130872200 & ALT=="A" ~ "L298Lsyn",
                          End==130874932 & ALT=="A" ~ "L384M",
                          End==130880101 & ALT=="C" ~ "F486S",
                          End==130880502 & ALT=="A" ~ "V506M",
                          End==130872171 & ALT=="A" ~ "V289I"))
d4=d4%>%
  mutate(ALT=alt,End=end,mutant=case_when(End==130872896 & ALT=="T" ~ "T315I",
                          End==130862970 & ALT=="C" ~ "Y253H",
                          End==130862977 & ALT=="T" ~ "E255V",
                          End==130873004 & ALT=="C" ~ "M351T",
                          End==130862962 & ALT=="A" ~ "G250E",
                          End==130874969 & ALT=="C" ~ "H396P",
                          End==130862955 & ALT=="G" ~ "L248V",
                          End==130874969 & ALT=="G" ~ "H396R",
                          End==130862971 & ALT=="T" ~ "Y253F",
                          End==130862969 & ALT=="T" ~ "Q252H",
                          End==130862976 & ALT=="A" ~ "E255K",
                          End==130872901 & ALT=="C" ~ "F317L",
                          End==130873027 & ALT=="C" ~ "F359L",
                          End==130873027 & ALT=="G" ~ "F359V",
                          End==130873027 & ALT=="A" ~ "F359I",
                          End==130873016 & ALT=="G" ~ "E355G",
                          End==130873016 & ALT=="C" ~ "E355A",
                          End==130878519 & ALT=="A" ~ "E459K",
                          End==130872911 & ALT=="G" ~ "Y320C",
                          End==130872133 & ALT=="G" ~ "D276G",
                          End==130862969 & ALT=="C" ~ "Q252Hsyn", ###The mutants below were found only in the ENU mutagenized pools
                          End==130872885 & ALT=="G" ~ "F311L",
                          End==130873028 & ALT=="G" ~ "F359C",
                          End==130874971 & ALT=="C" ~ "A397P",
                          End==130862854 & ALT=="G" ~ "H214R",
                          End==130872146 & ALT=="C" ~ "V280syn",
                          End==130872161 & ALT=="T" ~ "K285N",
                          End==130872923 & ALT=="G" ~ "L324R",
                          End==130872983 & ALT=="T" ~ "A344D",
                          End==130872145 & ALT=="A" ~ "V280E",
                          End==130872200 & ALT=="A" ~ "L298Lsyn",
                          End==130874932 & ALT=="A" ~ "L384M",
                          End==130880101 & ALT=="C" ~ "F486S",
                          End==130880502 & ALT=="A" ~ "V506M",
                          End==130872171 & ALT=="A" ~ "V289I"))

# ggplot(alldays,aes(x=time,y=alt_depth/depth))+geom_point(color="black",shape=21,size=3,aes(fill=mutant))+facet_wrap(~mutant)+cleanup+scale_y_continuous(trans = "log10",name="MAF")
```
```{r}
d0=d0%>%mutate(percent=alt_depth*100/depth)
d0$time="D0"
d2$time="D2"
d4$time="D4"
alldays=rbind(d0,d2,d4)
```

Novogene Lane 2 March 26th 2021
```{r}
d0=read.table("data/Consensus_Data/Novogene_lane2/10kmutants_inhouse/A10k.1.consensus.variant-calls.novogenelane2.mut",header=T,stringsAsFactors = F,sep="\t")
d2_300=read.table("data/Consensus_Data/Novogene_lane2/10kmutants_inhouse/Sp2_D2_300.1.consensus.variant-calls.novogenelane2.mut",header=T,stringsAsFactors = F,sep="\t")
d2_600=read.table("data/Consensus_Data/Novogene_lane2/10kmutants_inhouse/Sp2_D2_600.1.consensus.variant-calls.novogenelane2.mut",header=T,stringsAsFactors = F,sep="\t")
d4_300=read.table("data/Consensus_Data/Novogene_lane2/10kmutants_inhouse/Sp2_D4_300.1.consensus.variant-calls.novogenelane2.mut",header=T,stringsAsFactors = F,sep="\t")

d0=d0%>%filter(!alt%in%"<DEL>",alt_depth<=12000,variation_type%in%"snv")
d2_300=d2_300%>%filter(!alt%in%"<DEL>",alt_depth<=12000,variation_type%in%"snv")
d2_600=d2_600%>%filter(!alt%in%"<DEL>",alt_depth<=12000,variation_type%in%"snv")
d4_300=d4_300%>%filter(!alt%in%"<DEL>",alt_depth<=12000,variation_type%in%"snv")

d0=d0%>%
  mutate(ALT=alt,End=end,mutant=case_when(End==130872896 & ALT=="T" ~ "T315I",
                          End==130862970 & ALT=="C" ~ "Y253H",
                          End==130862977 & ALT=="T" ~ "E255V",
                          End==130873004 & ALT=="C" ~ "M351T",
                          End==130862962 & ALT=="A" ~ "G250E",
                          End==130874969 & ALT=="C" ~ "H396P",
                          End==130862955 & ALT=="G" ~ "L248V",
                          End==130874969 & ALT=="G" ~ "H396R",
                          End==130862971 & ALT=="T" ~ "Y253F",
                          End==130862969 & ALT=="T" ~ "Q252H",
                          End==130862976 & ALT=="A" ~ "E255K",
                          End==130872901 & ALT=="C" ~ "F317L",
                          End==130873027 & ALT=="C" ~ "F359L",
                          End==130873027 & ALT=="G" ~ "F359V",
                          End==130873027 & ALT=="A" ~ "F359I",
                          End==130873016 & ALT=="G" ~ "E355G",
                          End==130873016 & ALT=="C" ~ "E355A",
                          End==130878519 & ALT=="A" ~ "E459K",
                          End==130872911 & ALT=="G" ~ "Y320C",
                          End==130872133 & ALT=="G" ~ "D276G",
                          End==130862969 & ALT=="C" ~ "Q252Hsyn", ###The mutants below were found only in the ENU mutagenized pools
                          End==130872885 & ALT=="G" ~ "F311L",
                          End==130873028 & ALT=="G" ~ "F359C",
                          End==130874971 & ALT=="C" ~ "A397P",
                          End==130862854 & ALT=="G" ~ "H214R",
                          End==130872146 & ALT=="C" ~ "V280syn",
                          End==130872161 & ALT=="T" ~ "K285N",
                          End==130872923 & ALT=="G" ~ "L324R",
                          End==130872983 & ALT=="T" ~ "A344D",
                          End==130872145 & ALT=="A" ~ "V280E",
                          End==130872200 & ALT=="A" ~ "L298Lsyn",
                          End==130874932 & ALT=="A" ~ "L384M",
                          End==130880101 & ALT=="C" ~ "F486S",
                          End==130880502 & ALT=="A" ~ "V506M",
                          End==130872171 & ALT=="A" ~ "V289I"))

d2=d2_300%>%
  mutate(ALT=alt,End=end,mutant=case_when(End==130872896 & ALT=="T" ~ "T315I",
                          End==130862970 & ALT=="C" ~ "Y253H",
                          End==130862977 & ALT=="T" ~ "E255V",
                          End==130873004 & ALT=="C" ~ "M351T",
                          End==130862962 & ALT=="A" ~ "G250E",
                          End==130874969 & ALT=="C" ~ "H396P",
                          End==130862955 & ALT=="G" ~ "L248V",
                          End==130874969 & ALT=="G" ~ "H396R",
                          End==130862971 & ALT=="T" ~ "Y253F",
                          End==130862969 & ALT=="T" ~ "Q252H",
                          End==130862976 & ALT=="A" ~ "E255K",
                          End==130872901 & ALT=="C" ~ "F317L",
                          End==130873027 & ALT=="C" ~ "F359L",
                          End==130873027 & ALT=="G" ~ "F359V",
                          End==130873027 & ALT=="A" ~ "F359I",
                          End==130873016 & ALT=="G" ~ "E355G",
                          End==130873016 & ALT=="C" ~ "E355A",
                          End==130878519 & ALT=="A" ~ "E459K",
                          End==130872911 & ALT=="G" ~ "Y320C",
                          End==130872133 & ALT=="G" ~ "D276G",
                          End==130862969 & ALT=="C" ~ "Q252Hsyn", ###The mutants below were found only in the ENU mutagenized pools
                          End==130872885 & ALT=="G" ~ "F311L",
                          End==130873028 & ALT=="G" ~ "F359C",
                          End==130874971 & ALT=="C" ~ "A397P",
                          End==130862854 & ALT=="G" ~ "H214R",
                          End==130872146 & ALT=="C" ~ "V280syn",
                          End==130872161 & ALT=="T" ~ "K285N",
                          End==130872923 & ALT=="G" ~ "L324R",
                          End==130872983 & ALT=="T" ~ "A344D",
                          End==130872145 & ALT=="A" ~ "V280E",
                          End==130872200 & ALT=="A" ~ "L298Lsyn",
                          End==130874932 & ALT=="A" ~ "L384M",
                          End==130880101 & ALT=="C" ~ "F486S",
                          End==130880502 & ALT=="A" ~ "V506M",
                          End==130872171 & ALT=="A" ~ "V289I"))

d4=d4_300%>%
  mutate(ALT=alt,End=end,mutant=case_when(End==130872896 & ALT=="T" ~ "T315I",
                          End==130862970 & ALT=="C" ~ "Y253H",
                          End==130862977 & ALT=="T" ~ "E255V",
                          End==130873004 & ALT=="C" ~ "M351T",
                          End==130862962 & ALT=="A" ~ "G250E",
                          End==130874969 & ALT=="C" ~ "H396P",
                          End==130862955 & ALT=="G" ~ "L248V",
                          End==130874969 & ALT=="G" ~ "H396R",
                          End==130862971 & ALT=="T" ~ "Y253F",
                          End==130862969 & ALT=="T" ~ "Q252H",
                          End==130862976 & ALT=="A" ~ "E255K",
                          End==130872901 & ALT=="C" ~ "F317L",
                          End==130873027 & ALT=="C" ~ "F359L",
                          End==130873027 & ALT=="G" ~ "F359V",
                          End==130873027 & ALT=="A" ~ "F359I",
                          End==130873016 & ALT=="G" ~ "E355G",
                          End==130873016 & ALT=="C" ~ "E355A",
                          End==130878519 & ALT=="A" ~ "E459K",
                          End==130872911 & ALT=="G" ~ "Y320C",
                          End==130872133 & ALT=="G" ~ "D276G",
                          End==130862969 & ALT=="C" ~ "Q252Hsyn", ###The mutants below were found only in the ENU mutagenized pools
                          End==130872885 & ALT=="G" ~ "F311L",
                          End==130873028 & ALT=="G" ~ "F359C",
                          End==130874971 & ALT=="C" ~ "A397P",
                          End==130862854 & ALT=="G" ~ "H214R",
                          End==130872146 & ALT=="C" ~ "V280syn",
                          End==130872161 & ALT=="T" ~ "K285N",
                          End==130872923 & ALT=="G" ~ "L324R",
                          End==130872983 & ALT=="T" ~ "A344D",
                          End==130872145 & ALT=="A" ~ "V280E",
                          End==130872200 & ALT=="A" ~ "L298Lsyn",
                          End==130874932 & ALT=="A" ~ "L384M",
                          End==130880101 & ALT=="C" ~ "F486S",
                          End==130880502 & ALT=="A" ~ "V506M",
                          End==130872171 & ALT=="A" ~ "V289I"))

```

