---
title: "ABL_SM_CRISPR_Cut_Analyses"
author: "Haider Inam"
date: '2023-03-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath(".."))

library(stringr)
library(dplyr)
library(ggplot2)
library(plotly)
library(tictoc)
library(doParallel)
library(foreach)
library(RColorBrewer)
#Cleanup code for plotting
# 

```

```{r}
source("code/variantcaller/add_l298l.R")
for(i in c(1:18)){
  sample=paste("sample",i,sep = "")
  # sample="sample1"
  
  input_df_nol298l=read.csv(paste("data/Consensus_Data/novogene_lane18/",sample,"/nol298l/duplex/variant_caller_outputs/variants_unique_ann.csv",sep=""))
  input_df_l298l=read.csv(paste("data/Consensus_Data/novogene_lane18/",sample,"/l298l/duplex/variant_caller_outputs/variants_unique_ann.csv",sep=""))
  
  output_df=add_l298l(input_df_nol298l,input_df_l298l)
  write.csv(output_df,
            paste("data/Consensus_Data/novogene_lane18/",sample,"/duplex/variant_caller_outputs/variants_unique_ann.csv",sep = ""))  
}

input_df_nol298l=read.csv("data/Consensus_Data/novogene_lane18/sample9/nol298l/duplex/variant_caller_outputs/variants_unique_ann.csv")
input_df_l298l=read.csv("data/Consensus_Data/novogene_lane18/sample9/l298l/duplex/variant_caller_outputs/variants_unique_ann.csv")
  
output_df=add_l298l(input_df_nol298l,input_df_l298l)
write.csv(output_df,"data/Consensus_Data/novogene_lane18/sample9/duplex/variant_caller_outputs/variants_unique_ann.csv")  

```

```{r}
source("code/compare_screens.R")
source("code/plotting/cleanup.R")
source("code/plotting/heatmap_plotting_function.R")
# rm(list=ls())

comparisons=read.csv("data/Consensus_Data/novogene_lane18/TwistRegion1Screen_Comparisons_Todo.csv")
comparisons=comparisons%>%filter(Completed%in%"FALSE")

for(i in 1:nrow(comparisons)){
  dirname=comparisons$dirname[i]
  pathname=paste("output/ABLEnrichmentScreens/ABL_Region1_Lane18_Comparisons/",dirname,sep = "")
  # Create directory if it doesn't already exist
  if (!file.exists(pathname)){
    dir.create(pathname)
} 
before_screen1_identifier=unlist(strsplit(comparisons$before_screen1_identifier[i],","))
after_screen1_identifier=unlist(strsplit(comparisons$after_screen1_identifier[i],","))
before_screen2_identifier=unlist(strsplit(comparisons$before_screen2_identifier[i],","))
after_screen2_identifier=unlist(strsplit(comparisons$after_screen2_identifier[i],","))
  # length(after_screen1_identifier)
# screen_compare_means=compare_screens(comparisons$before_screen1_identifier[i],
#                                      comparisons$after_screen1_identifier[i],
#                                      comparisons$before_screen2_identifier[i],
#                                      comparisons$after_screen2_identifier[i])
screen_compare_means=compare_screens(before_screen1_identifier,
                                     after_screen1_identifier,
                                     before_screen2_identifier,
                                     after_screen2_identifier)

screen_compare_means_forexport=apply(screen_compare_means,2,as.character)
write.csv(screen_compare_means_forexport,file = paste("output/ABLEnrichmentScreens/ABL_Region1_Lane18_Comparisons/",dirname,"/screen_comparison_",dirname,".csv",sep=""))

# Plot 1. What does the heatmap look like from the average of the net growth rate?
heatmap_plotting_function(screen_compare_means,242,321,fill_variable = "netgr_obs_mean",fill_name = "Net growth rate")
ggsave(paste("output/ABLEnrichmentScreens/ABL_Region1_Lane18_Comparisons/",dirname,"/plot1_heatmap.pdf",sep=""),width=10,height=6,units="in",useDingbats=F)
# screen_compare_means2=screen_compare_means%>%filter(alt_codon%in%twist$Codon)

# Plot 2a: What do the correlations look like for net growth rate (show mutants in text)?
ggplot(screen_compare_means,aes(x=netgr_obs_screen1,y=netgr_obs_screen2,color=resmuts,label=species))+geom_text(size=2.5)+geom_abline()+cleanup+stat_cor(method = "pearson")+labs(color="Known\nResistant\nMutant")+scale_x_continuous("Net growth rate screen 1")+scale_y_continuous("Net growth rate screen 2")
ggsave(paste("output/ABLEnrichmentScreens/ABL_Region1_Lane18_Comparisons/",dirname,"/plot2a_Netgrowthrate_correlations_text.pdf",sep=""),width=6,height=4,units="in",useDingbats=F)

# Plot 2b: What do the correlations look like for enrichment scores (show mutants in points)?
ggplot(screen_compare_means,aes(x=netgr_obs_screen1,y=netgr_obs_screen2,label=species))+geom_point(color="black",shape=21,size=2,aes(fill=resmuts))+geom_abline()+cleanup+stat_cor(method = "pearson")+labs(fill="Known\nResistant\nMutant")+scale_x_continuous("Net growth rate screen 1")+scale_y_continuous("Net growth rate screen 2")
ggsave(paste("output/ABLEnrichmentScreens/ABL_Region1_Lane18_Comparisons/",dirname,"/plot2b_Netgrowthrate_correlations_points.pdf",sep=""),width=6,height=4,units="in",useDingbats=F)
# Plot 2c: What do the correlations look like for enrichment scores (show mutants in text)?
ggplot(screen_compare_means,aes(x=score_screen1,y=score_screen2,color=resmuts,label=species))+geom_text(size=2.5)+geom_abline()+cleanup+ stat_cor(method = "pearson")+labs(color="Known\nResistant\nMutant")+scale_x_continuous("Enrichment score screen 1")+scale_y_continuous("Enrichment score screen 2")
ggsave(paste("output/ABLEnrichmentScreens/ABL_Region1_Lane18_Comparisons/",dirname,"/plot2c_Enrichmentscores_correlations_text.pdf",sep=""),width=6,height=4,units="in",useDingbats=F)

# Plot 3a: Plots: what are the overall net growth rate distributions?
ggplot(screen_compare_means,aes(x=netgr_obs_mean,fill=resmuts))+geom_density(alpha=0.7)+cleanup+labs(fill="Known\nResistant\nMutant")+scale_x_continuous("Mean net growth rate of screens")
ggsave(paste("output/ABLEnrichmentScreens/ABL_Region1_Lane18_Comparisons/",dirname,"/plot3a_Netgrowthrate_distributions_resmuts.pdf",sep=""),width=6,height=4,units="in",useDingbats=F)
# Plot 3b: Plots: what are the net growth rate distributions?

library(reshape2)
screen_compare_melt=melt(screen_compare_means%>%dplyr::select(species,netgr_obs_screen1,netgr_obs_screen2),id.vars = "species",measure.vars =c("netgr_obs_screen1","netgr_obs_screen2"),variable.name = "Condition",value.name = "netgr_obs")


ggplot(screen_compare_melt,aes(x=netgr_obs,fill=Condition))+
  geom_density(alpha=0.7)+
  cleanup+
  scale_x_continuous("Net growth rate observed")+
  scale_fill_discrete(labels=c("Screen 1","Screen 2"))
ggsave(paste("output/ABLEnrichmentScreens/ABL_Region1_Lane18_Comparisons/",dirname,"/plot3b_Netgrowthrate_distributions.pdf",sep=""),width=6,height=4,units="in",useDingbats=F)

}

# dirname="K562_Medium_rep1vs2"

```


Doing some quick analysis on buried hydrophobic vs exposed residues
```{r}
dssp=read.csv("data/DSSP_SolventAccessibility_ABL/2hyy_dspp.csv",header = T)
dssp=dssp%>%mutate(RESIDUE=as.numeric(RESIDUE),ACC=as.numeric(ACC),AA=gsub("<ca>","",AA))
dssp=dssp%>%rename(protein_start=RESIDUE)

il3=read.csv("output/ABLEnrichmentScreens/ABL_Region1_Lane18_Comparisons/cross-replicate/baf3_IL3_rep1vsrep2_ft/screen_comparison_baf3_IL3_low_rep1vsrep2_ft.csv")
il3=il3%>%select(species,protein_start,netgr_obs_mean)
il3=il3%>%group_by(protein_start)%>%summarize(netgr_obs_mean=mean(netgr_obs_mean))

il3_dssp=merge(il3,dssp,by="protein_start")
il3_dssp=il3_dssp%>%mutate(exposed=case_when(ACC>=40~"Exposed",
                                            T~"Buried"))
ggplot(il3_dssp,aes(x=ACC))+geom_histogram()



ggplot(il3_dssp,aes(x=protein_start,y=netgr_obs_mean,color=exposed))+
  geom_point()+
  facet_wrap(~exposed,nrow=2)+
  scale_y_continuous("Mean net growth rate at residue")+
  scale_x_continuous("Residue on the ABL Kinase")+
  labs(color="Solvent \nAccessibility")+
  cleanup+theme(legend.position = c(.9,.85))+
  theme(
  strip.background = element_blank(),
  strip.text.x = element_blank()
)+theme(legend.background = element_rect(
                                  size=0.5, linetype="solid", 
                                  colour ="black"))
ggsave("data/DSSP_SolventAccessibility_ABL/il3solvent_accessibility_v1.pdf",width=6,height = 4,units="in",useDingbats=F)


ggplot(il3_dssp,aes(x=protein_start,y=netgr_obs_mean,color=exposed))+
  geom_point()+
  # facet_wrap(~exposed,nrow=2)+
  scale_y_continuous("Mean net growth rate at residue")+
  scale_x_continuous("Residue on the ABL Kinase")+
  labs(color="Solvent \nAccessibility")+cleanup
ggsave("data/DSSP_SolventAccessibility_ABL/il3solvent_accessibility_v2.pdf",width=6,height = 4,units="in",useDingbats=F)


ggplot(il3_dssp,aes(x=ACC,y=netgr_obs_mean,color=exposed))+
  geom_point()+
  scale_y_continuous("Mean net growth rate at residue")+
  scale_x_continuous("DSSP Solvent Accessibility at Residue")+
  cleanup+
  labs(color="Solvent \nAccessibility")+
  theme(legend.position = c(.9,.25))+
  theme(legend.background = element_rect(
                                  size=0.5, linetype="solid", 
                                  colour ="black"))
ggsave("data/DSSP_SolventAccessibility_ABL/il3solvent_accessibility_v3.pdf",width=6,height = 4,units="in",useDingbats=F)
```



Doing some quick analysis on buried hydrophobic vs exposed residues
```{r}
dssp=read.csv("data/DSSP_SolventAccessibility_ABL/2gqg_dspp.csv",header = T)
dssp=dssp%>%mutate(RESIDUE=as.numeric(RESIDUE),ACC=as.numeric(ACC),AA=gsub("<ca>","",AA))
dssp=dssp%>%rename(protein_start=RESIDUE)

il3=read.csv("output/ABLEnrichmentScreens/ABL_Region1_Lane18_Comparisons/cross-replicate/baf3_IL3_rep1vsrep2_ft/screen_comparison_baf3_IL3_low_rep1vsrep2_ft.csv")
il3=il3%>%select(species,protein_start,netgr_obs_mean)
il3=il3%>%group_by(protein_start)%>%summarize(netgr_obs_mean=mean(netgr_obs_mean))

il3_dssp=merge(il3,dssp,by="protein_start")
il3_dssp=il3_dssp%>%mutate(exposed=case_when(ACC>=40~"Exposed",
                                            T~"Buried"))
ggplot(il3_dssp,aes(x=ACC))+geom_histogram()



ggplot(il3_dssp,aes(x=protein_start,y=netgr_obs_mean,color=exposed))+
  geom_point()+
  facet_wrap(~exposed,nrow=2)+
  scale_y_continuous("Mean net growth rate at residue")+
  scale_x_continuous("Residue on the ABL Kinase")+
  labs(color="Solvent \nAccessibility")+
  cleanup+theme(legend.position = c(.9,.85))+
  theme(
  strip.background = element_blank(),
  strip.text.x = element_blank()
)+theme(legend.background = element_rect(
                                  size=0.5, linetype="solid", 
                                  colour ="black"))
# ggsave("data/DSSP_SolventAccessibility_ABL/il3solvent_accessibility_v1.pdf",width=6,height = 4,units="in",useDingbats=F)


ggplot(il3_dssp,aes(x=protein_start,y=netgr_obs_mean,color=exposed))+
  geom_point()+
  # facet_wrap(~exposed,nrow=2)+
  scale_y_continuous("Mean net growth rate at residue")+
  scale_x_continuous("Residue on the ABL Kinase")+
  labs(color="Solvent \nAccessibility")+cleanup
# ggsave("data/DSSP_SolventAccessibility_ABL/il3solvent_accessibility_v2.pdf",width=6,height = 4,units="in",useDingbats=F)


ggplot(il3_dssp,aes(x=ACC,y=netgr_obs_mean,color=exposed))+
  geom_point()+
  scale_y_continuous("Mean net growth rate at residue")+
  scale_x_continuous("DSSP Solvent Accessibility at Residue")+
  cleanup+
  labs(color="Solvent \nAccessibility")+
  theme(legend.position = c(.9,.25))+
  theme(legend.background = element_rect(
                                  size=0.5, linetype="solid", 
                                  colour ="black"))
# ggsave("data/DSSP_SolventAccessibility_ABL/il3solvent_accessibility_v3.pdf",width=6,height = 4,units="in",useDingbats=F)
```
