---
title: "barcodes_qc"
author: "Haider Inam"
date: '2022-10-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath(".."))

library(stringr)
library(dplyr)
library(ggplot2)
library(plotly)
library(tictoc)
library(doParallel)
library(foreach)
```

10.7.22
I will use these scripts for barcode QC and for coverage stats
```{r}
lane12=read.table("data/Consensus_Data/barcodes_lane12_lane13/sscs.barcodes.lane12.tsv")
names(lane12)=c("name","ct")
lane12$lane="lane12"
lane12$ct_norm=lane12$ct/sum(lane12$ct)

lane13=read.table("data/Consensus_Data/barcodes_lane12_lane13/sscs.barcodes.lane13.tsv")
names(lane13)=c("name","ct")
lane13$lane="lane13"
lane13$ct_norm=lane13$ct/sum(lane13$ct)

barcodes_combined=rbind(lane12,lane13)

plotly=ggplot(barcodes_combined,aes(x=ct,color=lane,alpha=0.5))+
  geom_density(adjust=3)+
  # facet_wrap(~lane)+
  # scale_x_continuous(limits=c(0,30))+
  scale_x_continuous(trans="log10",name="Barcode Count")
ggplotly(plotly)

sum(as.numeric(lane12$ct<=5))
sum(as.numeric(lane12$ct<=500))

sum(as.numeric(lane13$ct<=5))


plotly=ggplot(barcodes_combined,aes(x=ct_norm,fill=lane,alpha=0.5))+
  geom_density()+
  # facet_wrap(~lane)+
  scale_x_continuous(name="Normalized Counts")
ggplotly(plotly)
```

