---
title: "E255K_alphas_figure"
author: "Haider Inam"
date: "5/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("lmtest")
library("ggplot2")
library("MASS")
library("fitdistrplus")
library("lme4")
library("boot")
library("dplyr")
library("plotly")
library("reshape2")
```


```{r}
# rm(list=ls())

conc_for_predictions=0.8
net_gr_wodrug=0.05

# twinstrand_simple_melt_merge=read.csv("../output/twinstrand_simple_melt_merge.csv",header = T,stringsAsFactors = F)
twinstrand_simple_melt_merge=read.csv("output/twinstrand_simple_melt_merge.csv",header = T,stringsAsFactors = F)

# twinstrand_maf_merge=read.csv("../output/twinstrand_maf_merge.csv",header = T,stringsAsFactors = F)
twinstrand_maf_merge=read.csv("output/twinstrand_maf_merge.csv",header = T,stringsAsFactors = F)

# ic50data_long=read.csv("../output/ic50data_all_conc.csv",header = T,stringsAsFactors = F)
ic50data_long=read.csv("output/ic50data_all_conc.csv",header = T,stringsAsFactors = F)
ic50data_long$netgr_pred=net_gr_wodrug-ic50data_long$drug_effect

gfpdata=read.table("data/gfpenrichmentdata.csv",stringsAsFactors = F,header = T,sep=',')
# gfpdata=read.table("../data/gfpenrichmentdata.csv",stringsAsFactors = F,header = T,sep=',')


# ic50_heatmap=read.csv("../data/IC50HeatMap.csv",header = T,stringsAsFactors = F)
ic50_heatmap=read.csv("data/IC50HeatMap.csv",header = T,stringsAsFactors = F)

cleanup=theme_bw() +
  theme(plot.title = element_text(hjust=.5),
        panel.grid.major = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(color = "black"),
        axis.text = element_text(face="bold",color="black",size="11"),
        text=element_text(size=11,face="bold"),
        axis.title=element_text(face="bold",size="11"))
```

This boxplot will compare the net growth rates of E255K observed across IC50s, FACs studies, and pooled studies

```{r}
###########Netgr from pooled approach###########
pooled_data=twinstrand_simple_melt_merge%>%filter(mutant=="E255K",!netgr_obs%in%NA,duration%in%c("d0d3","d0d6"))%>%dplyr::select(mutant,experiment,netgr=netgr_obs,Spike_in_freq)%>%mutate(measurement="Pooled")
pooled_data=pooled_data%>%dplyr::select(measurement,netgr)
# pooled_data=twinstrand_simple_melt_merge%>%filter(mutant=="E255K",!netgr_obs%in%NA)
#Why does the GFP FACs data seem to have the same growth rates?

###########Netgr from IC50s###########
ic50_data=ic50_heatmap%>%filter(species=="E255K")%>%dplyr::select(mutant=species,y=X1.25)
ic50_data=ic50_data%>%mutate(alpha=-log(y)/72)
ic50_data=ic50_data%>%mutate(netgr=net_gr_wodrug-alpha,measurement="IC50s")
ic50_data=ic50_data%>%dplyr::select(measurement,netgr)

###########Netgr from FACs experiment###########
#This data originally sits in the FACs entries in the "Mixing Experiment 4, 8/20/18, directory on benchling"
#These are for both 1:1000 and 1:100 data. Growth rates looked similar at low frequencies with and without WT effects but there was a slowering of growth without WT spike-ins. We haven't focused on that here though
facs_data=data.frame(c(0.046483696,0.0450497374,0.0197837978,0.0437170827,0.04520188,0.0440885505))
colnames(facs_data)="netgr"
facs_data=facs_data%>%mutate(mutant="E255K",Spike_in_freq=c(1000,1000,1000,10000,10000,10000),measurement="FACS")
facs_data=facs_data%>%dplyr::select(measurement,netgr)


###########Plotting###########
###Please note that 625nM imatinib was used in all conditions
e255k_gr=rbind(facs_data,pooled_data,ic50_data)
ggplot(e255k_gr,aes(x=factor(measurement),y=netgr,fill=factor(measurement)))+geom_boxplot()+scale_fill_manual(values = c("#63A088","#1CCE16","#206A36"))+cleanup+scale_y_continuous(name="Net Grwoth Rate Observed")

ggplot(e255k_gr,aes(x=factor(measurement),y=log(2)/netgr,fill=factor(measurement)))+geom_boxplot()+scale_fill_manual(values = c("#63A088","#1CCE16","#206A36"))+cleanup+scale_y_continuous(limits=c(0,30),name="Doubling Time")

a=twinstrand_simple_melt_merge%>%filter(mutant=="E255K",!netgr_obs%in%NA)

#There seems to be a bit of a signal with the growth rates from D0 to D3 and D3 to D6. D0D3 seems to be a little higher. Will look at that discrepancy later.
```


```{r}
gfpdata$ttotal_sequenced=c(0,3,6)
gfpdata$xtotal_sequenced=c(129,3323,37023)
# gfpdata_simple=gfpdata%>%dplyr::select(ttotal_4,xtotal_4_e255k)
# e255k=twinstrand_maf_merge%>%filter(mutant=="E255K",experiment=="M3")

gfpplotlog=ggplot(gfpdata)+
  geom_line(aes(x=t_out_4,y=log10(x_out_4_e255k)),color="#1cce16",size=1.5)+geom_ribbon(aes(x = t_out_4_conintub,ymax=log10(x_out_4_e255k_ciub),ymin=log10(x_out_4_e255k_cilb)),fill="#1cce16",alpha=.3)+
  geom_line(aes(x=t_out_3,y=log10(x_out_3_e255k)),color="#206A36",size=1.5)+geom_ribbon(aes(x = t_out_3_conintub,ymax=log10(x_out_3_e255k_ciub),ymin=log10(x_out_3_e255k_cilb)),fill="#206A36",alpha=.3)+
  geom_point(aes(x=ttotal_4,y=log10(xtotal_4_e255k)),size=3)+
  geom_point(aes(x=ttotal_3,y=log10(xtotal_3_e255k)),size=3)+
  geom_point(aes(x=ttotal_sequenced,y=log10(xtotal_sequenced)),size=3,shape="square",color="blue")+
  theme_bw()+theme(plot.title = element_text(hjust=.5),text = element_text(size=24),axis.title = element_text(face="bold",size="19"),axis.text=element_text(face="bold",size="19"))+
  xlim(0,7)+
  scale_y_continuous(labels=parse(text = c("10^3","10^5")),limits = c(2,6.5),breaks = c(3,5))+
  # scale_y_continuous(labels = function(x) format(x, scientific = TRUE), limits = c(1e2,5e6),trans='log10',labels=parse(text = c("10^3","10^5"))+
  # scale_y_continuous(labels = parse(text = c("10^3","10^5")), limits = c(1e2,5e6),trans='log10')+
  ylab('Resistant Population')+
  xlab('Time (Days)')
gfpplotlog
```
Looking at the growth rate changes with dates
```{r}
a=twinstrand_simple_melt_merge%>%filter(duration%in%c("d0d3","d3d6"),experiment%in%c("M3","M6"))
plotly=ggplot(a,aes(x=factor(mutant),y=netgr_obs,fill=duration))+geom_col(position="dodge",stat="identity")+facet_wrap(~experiment)
ggplotly(plotly)
#Realizing that the signal I'm seeing here might be confounded by erroneous flow cytometry counts... 
```

