---
title: "K562_BCRABL_Analysis"
author: "Haider Inam"
date: '2022-12-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# knitr::opts_knit$set(root.dir = normalizePath(".."))

library(stringr)
library(dplyr)
library(ggplot2)
library(plotly)
library(tictoc)
library(doParallel)
library(foreach)
library(RColorBrewer)
#Cleanup code for plotting
cleanup=theme_bw() +
  theme(plot.title = element_text(hjust=.5), 
        panel.grid.major = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(color = "black"),
        axis.text = element_text(face="bold",color="black",size="11"),
        text=element_text(size=11,face="bold"),
        axis.title=element_text(face="bold",size="11"))
source("code/depth_finder.R")
```


Looking at the evenness of the K562 Library
```{r}
k562=read.csv("data/Consensus_Data/Novogene_lane14/sample9/sscs/variant_caller_outputs/variants_unique_ann.csv")
k562$sample="k562"

k562=k562%>%
  rowwise()%>%
  mutate(ref_aa=strsplit(amino_acids,"/")[[1]][1],
         alt_aa=strsplit(amino_acids,"/")[[1]][2])
k562=k562%>%mutate(maf=ct/depth)

k562=k562%>%mutate(region=case_when(protein_start<250&protein_start>=242~1,
                                              protein_start<258&protein_start>=250~2,
                                              protein_start<266&protein_start>=258~3,
                                              protein_start<274&protein_start>=266~4,
                                              protein_start<282&protein_start>=274~5,
                                              protein_start<290&protein_start>=282~6,
                                              protein_start<298&protein_start>=290~7,
                                              protein_start<306&protein_start>=298~8,
                                              protein_start<314&protein_start>=306~9,
                                              protein_start<322&protein_start>=314~10,
                                              protein_start<330&protein_start>=322~11,
                                              protein_start<338&protein_start>=330~12,
                                              protein_start<346&protein_start>=338~13,
                                              protein_start<354&protein_start>=346~14,
                                              protein_start<362&protein_start>=354~15,
                                              protein_start<370&protein_start>=362~16,
                                              protein_start<378&protein_start>=370~17,
                                              protein_start<386&protein_start>=378~18,
                                              protein_start<394&protein_start>=386~19,
                                              protein_start<402&protein_start>=394~20,
                                              protein_start<410&protein_start>=402~21,
                                              protein_start<418&protein_start>=410~22,
                                              protein_start<426&protein_start>=418~23,
                                              protein_start<434&protein_start>=426~24,
                                              protein_start<442&protein_start>=434~25,
                                              protein_start<450&protein_start>=442~26,
                                              protein_start<458&protein_start>=450~27,
                                              protein_start<466&protein_start>=458~28,
                                              protein_start<474&protein_start>=466~29,
                                              protein_start<482&protein_start>=474~30,
                                              protein_start<490&protein_start>=482~31,
                                              protein_start<498&protein_start>=490~32,
                                              T~0))
library(RColorBrewer)
getPalette = colorRampPalette(brewer.pal(33, "Set2"))


k562=k562%>%rowwise()%>%mutate(ID=paste(protein_start,amino_acids,sep=""))
plotly=ggplot(k562%>%filter(consequence_terms%in%"missense_variant",protein_start>=242,protein_start<=494),aes(x=protein_start,y=ct))+geom_col(color="black",aes(fill=factor(region)))+scale_fill_manual(values=getPalette(33))
ggplotly(plotly)


library("pals")
ggplot(k562%>%filter(nchar(alt_aa)%in%1,!alt_aa%in%NA,consequence_terms%in%"missense_variant",protein_start>=242,protein_start<=494),aes(x=protein_start,y=ct,fill=factor(alt_aa)))+
  geom_bar(stat="identity",position="fill")+
  scale_x_continuous(expand = c(0,0),name="Position Along ABL Kinase",breaks=c(242,300,350,400,450,490))+
  scale_y_continuous(expand = c(0,0),name="%Variant AA")+theme(plot.title = element_text(hjust = 0.5))+
  scale_fill_manual(values=as.vector(stepped(21)))+
  cleanup+
  theme(legend.title = element_blank(),
  legend.position = "right")+
  guides(fill=guide_legend(ncol=2))

# ggsave("k562_bcrabl_background.pdf",width=12,height=4,units="in",useDingbats=F)
```

How many unique mutants are there per residue in the K562 library
```{r}
calls_sum=k562%>%filter(consequence_terms%in%"missense_variant")%>%group_by(protein_start)%>%summarize(unique_mutants=n(),count=sum(ct))

calls_sum=calls_sum%>%mutate(region=case_when(protein_start<250&protein_start>=242~1,
                                              protein_start<258&protein_start>=250~2,
                                              protein_start<266&protein_start>=258~3,
                                              protein_start<274&protein_start>=266~4,
                                              protein_start<282&protein_start>=274~5,
                                              protein_start<290&protein_start>=282~6,
                                              protein_start<298&protein_start>=290~7,
                                              protein_start<306&protein_start>=298~8,
                                              protein_start<314&protein_start>=306~9,
                                              protein_start<322&protein_start>=314~10,
                                              protein_start<330&protein_start>=322~11,
                                              protein_start<338&protein_start>=330~12,
                                              protein_start<346&protein_start>=338~13,
                                              protein_start<354&protein_start>=346~14,
                                              protein_start<362&protein_start>=354~15,
                                              protein_start<370&protein_start>=362~16,
                                              protein_start<378&protein_start>=370~17,
                                              protein_start<386&protein_start>=378~18,
                                              protein_start<394&protein_start>=386~19,
                                              protein_start<402&protein_start>=394~20,
                                              protein_start<410&protein_start>=402~21,
                                              protein_start<418&protein_start>=410~22,
                                              protein_start<426&protein_start>=418~23,
                                              protein_start<434&protein_start>=426~24,
                                              protein_start<442&protein_start>=434~25,
                                              protein_start<450&protein_start>=442~26,
                                              protein_start<458&protein_start>=450~27,
                                              protein_start<466&protein_start>=458~28,
                                              protein_start<474&protein_start>=466~29,
                                              protein_start<482&protein_start>=474~30,
                                              protein_start<490&protein_start>=482~31,
                                              protein_start<498&protein_start>=490~32,
                                              T~0))
getPalette = colorRampPalette(brewer.pal(33, "Set2"))
plotly=ggplot(calls_sum%>%filter(protein_start>=242,protein_start<=494),aes(x=protein_start,y=unique_mutants))+geom_col(color="black",aes(fill=factor(region)))+cleanup+scale_fill_manual(values=getPalette(33))
ggplotly(plotly)
```
