---
title: "ABL_allregions_analysis"
author: "Haider Inam"
date: '2023-08-10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath(".."))
# rm(list=ls())

library(stringr)
library(dplyr)
library(ggplot2)
library(plotly)
library(tictoc)
library(doParallel)
library(foreach)
library(RColorBrewer)
library(ggpubr)
library(pROC)
```

```{r}
#Cleanup code for plotting
source("code/plotting/cleanup.R")
source("code/compare_screens.R")
source("code/plotting/heatmap_plotting_function.R")
```



```{r}
# setwd("OneDrive - The Pennsylvania State University/RProjects/duplex_sequencing_screen/")

source("code/merge_samples.R")
getwd()
source("code/res_residues_adder.R")

# Region 2:
a=merge_samples("Novogene_lane19_20/Ln19a_Sample2/sscs","Novogene_lane19_20/Ln19a_Sample3/sscs")
ggplot(a%>%filter(!alt_aa%in%"O",protein_start>320,protein_start<394),aes(x=protein_start,y=alt_aa,fill=ct))+geom_tile()


# Region 3:
# b=merge_samples("novogene_lane23/Lane23_Sample19/sscs","Novogene_lane19_20/Ln19b_Sample9/sscs")
b=read.csv("data/Consensus_Data/novogene_lane19_20/Ln19a_Sample11/sscs/variant_caller_outputs/variants_unique_ann.csv")
ggplot(b%>%filter(!alt_aa%in%"O",protein_start>393,protein_start<465),aes(x=protein_start,y=alt_aa,fill=ct))+geom_tile()


# Region 4:
b=merge_samples("novogene_lane23/Sample19/sscs","Novogene_lane19_20/Ln19b_Sample9/sscs")
ggplot(b%>%filter(!alt_aa%in%"O",protein_start>464,protein_start<520),aes(x=protein_start,y=alt_aa,fill=ct))+geom_tile()
```

```{r}
cellcounts_matrix_dir="data/Consensus_Data/novogene_lane23/TwistAllRegions_CellCounts_Matrix.csv"

comparisons=read.csv("data/Consensus_Data/novogene_lane23/TwistAllRegions_Comparisons_Todo.csv")
comparisons=comparisons%>%filter(Completed%in%"FALSE")

# for(i in 1:nrow(comparisons)){
for(i in 6:8){
  # i=10
  dirname=comparisons$dirname[i]
  pathname=paste("output/ABLEnrichmentScreens/ABL_Region234_Comparisons/",dirname,sep = "")
  # Create directory if it doesn't already exist
  if (!file.exists(pathname)){
    dir.create(pathname)
} 
before_screen1_identifier=unlist(strsplit(comparisons$before_screen1_identifier[i],","))
after_screen1_identifier=unlist(strsplit(comparisons$after_screen1_identifier[i],","))
before_screen2_identifier=unlist(strsplit(comparisons$before_screen2_identifier[i],","))
after_screen2_identifier=unlist(strsplit(comparisons$after_screen2_identifier[i],","))
  # length(after_screen1_identifier)
# screen_compare_means=compare_screens(comparisons$before_screen1_identifier[i],
#                                      comparisons$after_screen1_identifier[i],
#                                      comparisons$before_screen2_identifier[i],
#                                      comparisons$after_screen2_identifier[i])
screen_compare_means=compare_screens(before_screen1_identifier,
                                     after_screen1_identifier,
                                     before_screen2_identifier,
                                     after_screen2_identifier,
                                     cellcounts_matrix_dir)

screen_compare_means_forexport=apply(screen_compare_means,2,as.character)
write.csv(screen_compare_means_forexport,file = paste("output/ABLEnrichmentScreens/ABL_Region234_Comparisons/",dirname,"/screen_comparison_",dirname,".csv",sep=""))



# Plot 1. What does the heatmap look like from the average of the net growth rate?
start_site=comparisons$ABL_Start[i]
end_site=comparisons$ABL_End[i]

heatmap_plotting_function(screen_compare_means,start_site,end_site,fill_variable = "netgr_obs_mean",fill_name = "Net growth rate")
ggsave(paste("output/ABLEnrichmentScreens/ABL_Region234_Comparisons/",dirname,"/plot1_heatmap.pdf",sep=""),width=10,height=6,units="in",useDingbats=F)
# screen_compare_means2=screen_compare_means%>%filter(alt_codon%in%twist$Codon)

# Plot 2a: What do the correlations look like for net growth rate (show mutants in text)?
ggplot(screen_compare_means,aes(x=netgr_obs_screen1,y=netgr_obs_screen2,color=resmuts,label=species))+geom_text(size=2.5)+geom_abline()+cleanup+stat_cor(method = "pearson")+labs(color="Known\nResistant\nMutant")+scale_x_continuous("Net growth rate screen 1")+scale_y_continuous("Net growth rate screen 2")
ggsave(paste("output/ABLEnrichmentScreens/ABL_Region234_Comparisons/",dirname,"/plot2a_Netgrowthrate_correlations_text.pdf",sep=""),width=6,height=4,units="in",useDingbats=F)

# Plot 2b: What do the correlations look like for enrichment scores (show mutants in points)?
ggplot(screen_compare_means,aes(x=netgr_obs_screen1,y=netgr_obs_screen2,label=species))+geom_point(color="black",shape=21,size=2,aes(fill=resmuts))+geom_abline()+cleanup+stat_cor(method = "pearson")+labs(fill="Known\nResistant\nMutant")+scale_x_continuous("Net growth rate screen 1")+scale_y_continuous("Net growth rate screen 2")
ggsave(paste("output/ABLEnrichmentScreens/ABL_Region234_Comparisons/",dirname,"/plot2b_Netgrowthrate_correlations_points.pdf",sep=""),width=6,height=4,units="in",useDingbats=F)
# Plot 2c: What do the correlations look like for enrichment scores (show mutants in text)?
ggplot(screen_compare_means,aes(x=score_screen1,y=score_screen2,color=resmuts,label=species))+geom_text(size=2.5)+geom_abline()+cleanup+ stat_cor(method = "pearson")+labs(color="Known\nResistant\nMutant")+scale_x_continuous("Enrichment score screen 1")+scale_y_continuous("Enrichment score screen 2")
ggsave(paste("output/ABLEnrichmentScreens/ABL_Region234_Comparisons/",dirname,"/plot2c_Enrichmentscores_correlations_text.pdf",sep=""),width=6,height=4,units="in",useDingbats=F)

# Plot 3a: Plots: what are the overall net growth rate distributions?
ggplot(screen_compare_means,aes(x=netgr_obs_mean,fill=resmuts))+geom_density(alpha=0.7)+cleanup+labs(fill="Known\nResistant\nMutant")+scale_x_continuous("Mean net growth rate of screens")
ggsave(paste("output/ABLEnrichmentScreens/ABL_Region234_Comparisons/",dirname,"/plot3a_Netgrowthrate_distributions_resmuts.pdf",sep=""),width=6,height=4,units="in",useDingbats=F)
# Plot 3b: Plots: what are the net growth rate distributions?

library(reshape2)
screen_compare_melt=melt(screen_compare_means%>%dplyr::select(species,netgr_obs_screen1,netgr_obs_screen2),id.vars = "species",measure.vars =c("netgr_obs_screen1","netgr_obs_screen2"),variable.name = "Condition",value.name = "netgr_obs")


ggplot(screen_compare_melt,aes(x=netgr_obs,fill=Condition))+
  geom_density(alpha=0.7)+
  cleanup+
  scale_x_continuous("Net growth rate observed")+
  scale_fill_discrete(labels=c("Screen 1","Screen 2"))
ggsave(paste("output/ABLEnrichmentScreens/ABL_Region234_Comparisons/",dirname,"/plot3b_Netgrowthrate_distributions.pdf",sep=""),width=6,height=4,units="in",useDingbats=F)

}

# dirname="K562_Medium_rep1vs2"

```

I have new sequencing data from Lane 27b and Lane 28.
For BTR4D0: I'll look at the correlation between lane 28 sample 17 and lane 27b sample 9
```{r}
# source("code/merge_samples.R")
# source("code/compare_samples.R")
# source("code/compare_samples_archive.R")

btr4d0a=read.csv("data/Consensus_Data/novogene_lane28/sample17/sscs/variant_caller_outputs/variants_unique_ann.csv")
btr4d0a=btr4d0a%>%filter(consequence_terms%in%"missense_variant",!ct%in%c(1,2,3))%>%mutate(maf=ct/depth)
btr4d0a=btr4d0a%>%dplyr::select(ref_aa,protein_start,alt_aa,type,maf,alt_codon)

btr4d0b=read.csv("data/Consensus_Data/novogene_lane27b/BR4D0_Sample9_10/sscs/variant_caller_outputs/variants_unique_ann.csv")
btr4d0b=btr4d0b%>%filter(consequence_terms%in%"missense_variant",!ct%in%c(1,2,3))%>%mutate(maf=ct/depth)
btr4d0b=btr4d0b%>%dplyr::select(ref_aa,protein_start,alt_aa,type,maf,alt_codon)

btr4d0=merge(btr4d0a,btr4d0b,by = c("ref_aa","protein_start","alt_aa","type","alt_codon"))
btr4d0=btr4d0%>%filter(alt_codon%in%twist_alt_codon)
btr4d0=btr4d0%>%mutate(species=paste(ref_aa,protein_start,alt_aa,sep=""))
ggplot(btr4d0,
       aes(x=maf.x,y=maf.y,color=type))+geom_point()+
  scale_x_continuous(trans="log10")+
  scale_y_continuous(trans="log10")+
  stat_cor(method = "pearson")


ggplot(btr4d0,
       aes(x=maf.x,y=maf.y,color=type,label=species))+
  geom_text()+
  scale_x_continuous(trans="log10")+
  scale_y_continuous(trans="log10")+
  stat_cor(method = "pearson")
# btr4d0=btr4d0%>%filter(species%in%"Q491V")
btr4d0a=btr4d0a%>%filter(ref_aa%in%"Q",protein_start%in%491)
btr4d0b=btr4d0b%>%filter(ref_aa%in%"Q",protein_start%in%491)
```
For BTR4DMD6A vs B: I'll look at the correlation between lane 28 sample 22 and lane 27b sample 11_12
```{r}
# source("code/merge_samples.R")
# source("code/compare_samples.R")
# source("code/compare_samples_archive.R")

btr4d0a=read.csv("data/Consensus_Data/novogene_lane28/sample22/sscs/variant_caller_outputs/variants_unique_ann.csv")
btr4d0a=btr4d0a%>%filter(consequence_terms%in%"missense_variant",!ct%in%c(1,2,3))%>%mutate(maf=ct/depth)
btr4d0a=btr4d0a%>%dplyr::select(ref_aa,protein_start,alt_aa,type,maf,alt_codon)

btr4d0b=read.csv("data/Consensus_Data/novogene_lane27b/BR4D6_Sample11_12/sscs/variant_caller_outputs/variants_unique_ann.csv")
btr4d0b=btr4d0b%>%filter(consequence_terms%in%"missense_variant",!ct%in%c(1,2,3))%>%mutate(maf=ct/depth)
btr4d0b=btr4d0b%>%dplyr::select(ref_aa,protein_start,alt_aa,type,maf,alt_codon)

btr4d0=merge(btr4d0a,btr4d0b,by = c("ref_aa","protein_start","alt_aa","type","alt_codon"))
btr4d0b=btr4d0b%>%dplyr::select(ref_aa,protein_start,alt_aa,type,maf,alt_codon)

btr4d0=merge(btr4d0a,btr4d0b,by = c("ref_aa","protein_start","alt_aa","type","alt_codon"))
btr4d0=btr4d0%>%filter(alt_codon%in%twist_alt_codon)
btr4d0=btr4d0%>%mutate(species=paste(ref_aa,protein_start,alt_aa,sep=""))

ggplot(btr4d0,
       aes(x=maf.x,y=maf.y,color=type))+geom_point()+
  scale_x_continuous(trans="log10")+
  scale_y_continuous(trans="log10")+
  stat_cor(method = "pearson")

ggplot(btr4d0,
       aes(x=maf.x,y=maf.y,color=type,label=species))+
  geom_text()+
  scale_x_continuous(trans="log10")+
  scale_y_continuous(trans="log10")+
  stat_cor(method = "pearson")

```

For BTR4DHD6A vs B: I'll look at the correlation between
 lane 28 sample 23 and 24
```{r}
# source("code/merge_samples.R")
# source("code/compare_samples.R")
# source("code/compare_samples_archive.R")

btr4d0a=read.csv("data/Consensus_Data/novogene_lane28/sample23/sscs/variant_caller_outputs/variants_unique_ann.csv")
btr4d0a=btr4d0a%>%filter(consequence_terms%in%"missense_variant",!ct%in%c(1,2,3))%>%mutate(maf=ct/depth)
btr4d0a=btr4d0a%>%dplyr::select(ref_aa,protein_start,alt_aa,type,maf,alt_codon)

btr4d0b=read.csv("data/Consensus_Data/novogene_lane28/sample24/sscs/variant_caller_outputs/variants_unique_ann.csv")
btr4d0b=btr4d0b%>%filter(consequence_terms%in%"missense_variant",!ct%in%c(1,2,3))%>%mutate(maf=ct/depth)
btr4d0b=btr4d0b%>%dplyr::select(ref_aa,protein_start,alt_aa,type,maf,alt_codon)

btr4d0=merge(btr4d0a,btr4d0b,by = c("ref_aa","protein_start","alt_aa","type","alt_codon"))
btr4d0=btr4d0%>%filter(alt_codon%in%twist_alt_codon)
btr4d0=btr4d0%>%mutate(species=paste(ref_aa,protein_start,alt_aa,sep=""))

ggplot(btr4d0,
       aes(x=maf.x,y=maf.y,color=type))+geom_point()+
  scale_x_continuous(trans="log10")+
  scale_y_continuous(trans="log10")+
  stat_cor(method = "pearson")

ggplot(btr4d0,
       aes(x=maf.x,y=maf.y,color=type,label=species))+
  geom_text()+
  scale_x_continuous(trans="log10")+
  scale_y_continuous(trans="log10")+
  stat_cor(method = "pearson")

```
```{r}
codon_table=read.csv("data/codon_table.csv",header = T,stringsAsFactors = F)
twist_codons=codon_table%>%filter(Twist%in%T)
  # twist_alt_codon=twist_codons[twist_codons$Letter%in%alt_aa,"Codon"]
twist_alt_codon=twist_codons[,"Codon"]
```

For BTR4DID6A vs B: I'll look at the correlation between
 lane 28 sample 18 and 19
```{r}
# source("code/merge_samples.R")
# source("code/compare_samples.R")
# source("code/compare_samples_archive.R")

btr4d0a=read.csv("data/Consensus_Data/novogene_lane28/sample18/sscs/variant_caller_outputs/variants_unique_ann.csv")
btr4d0a=btr4d0a%>%filter(consequence_terms%in%"missense_variant",!ct%in%c(1,2,3,4,5,6))%>%mutate(maf=ct/depth)
btr4d0a=btr4d0a%>%dplyr::select(ref_aa,protein_start,alt_aa,type,maf,alt_codon)

btr4d0b=read.csv("data/Consensus_Data/novogene_lane28/sample19/sscs/variant_caller_outputs/variants_unique_ann.csv")
btr4d0b=btr4d0b%>%filter(consequence_terms%in%"missense_variant",!ct%in%c(1,2,3,4,5,6))%>%mutate(maf=ct/depth)
btr4d0b=btr4d0b%>%dplyr::select(ref_aa,protein_start,alt_aa,type,maf,alt_codon)

btr4d0=merge(btr4d0a,btr4d0b,by = c("ref_aa","protein_start","alt_aa","type","alt_codon"))
# btr4d0=btr4d0%>%filter(!alt_codon%in%twist_alt_codon)
btr4d0=btr4d0%>%filter(alt_codon%in%twist_alt_codon)
btr4d0=btr4d0%>%mutate(species=paste(ref_aa,protein_start,alt_aa,sep=""))

ggplot(btr4d0,
       aes(x=maf.x,y=maf.y,color=type))+geom_point()+
  scale_x_continuous(trans="log10")+
  scale_y_continuous(trans="log10")+
  stat_cor(method = "pearson")


ggplot(btr4d0,
       aes(x=maf.x,y=maf.y,color=type,label=species))+
  geom_text()+
  scale_x_continuous(trans="log10")+
  scale_y_continuous(trans="log10")+
  stat_cor(method = "pearson")

```
