---
title: "SSCSvsTileseq"
author: "Haider Inam"
date: '2024-12-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath(".."))

library(stringr)
library(dplyr)
library(ggplot2)
library(plotly)
library(tictoc)
library(doParallel)
library(foreach)
library(RColorBrewer)
library("ggrepel")
library(reshape2)
```

```{r}
source("code/resmuts_adder.R")
#Cleanup code for plotting
cleanup=theme_bw() +
  theme(plot.title = element_text(hjust=.5),
        panel.grid.major = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.background = element_blank(),
        # axis.line = element_line(color = "black"),
        axis.text = element_text(face="bold",color="black",size="11"),
        text=element_text(size=11,face="bold"),
        axis.title=element_text(face="bold",size="11"))
```

This is the analysis to allow benchmarking of ABL data to tileseq data

This google doc has notes on how to interpret the google doc
```{r}
# rm(list=ls())
a=data%>%filter(is_intended%in%0,seqtech%in%"sscs",dose%in%"300nM",protein_start%in%c(242:512))
data=read.csv("output/ABLEnrichmentScreens/ABL_Region1234_Tileseq/data/TileSeqandSSCS_full_kinase_alldoses_with_lfc_corrected_netgrowths_12192024.csv",header = T,stringsAsFactors = F)

ggplot(data,aes(x=factor(protein_start),y=ct_screen1_before,fill=factor(is_intended)))+geom_boxplot()+facet_wrap(~seqtech,nrow = 2)+cleanup+scale_y_continuous(trans="log10")+theme(axis.text.x=element_text(angle=90, hjust=1))



data_snr=data%>%filter(protein_start%in%c(242:512),!protein_start%in%c(354:361))%>%group_by(seqtech,dose,is_intended,protein_start)%>%summarize(nmuts=n(),coverage_mean=mean(ct_screen1_before),depth_mean=mean(depth_screen1_before))

data_snr_cast <- data_snr %>%
  pivot_wider(
    names_from = is_intended,
    values_from = c(nmuts,coverage_mean,depth_mean),
    names_glue = "{.value}_{ifelse(is_intended == 1, 'intended', 'unintended')}"
  )
data_snr_cast=data_snr_cast%>%mutate(snr=coverage_mean_intended/coverage_mean_unintended)

ggplot(data_snr_cast%>%filter(dose%in%"300nM"),aes(x=protein_start,y=snr))+geom_point()+facet_wrap(~seqtech)+scale_y_continuous(limits=c(0,60))

ggplot(data_snr_cast%>%filter(dose%in%"300nM"),aes(x=snr,fill=seqtech))+geom_density(alpha=0.6)+scale_x_continuous("Signal to noise",trans="log10")

ggplot(data_snr_cast%>%filter(dose%in%"300nM"),aes(x=protein_start,y=nmuts_intended))+geom_point()+facet_wrap(~seqtech)

ggplot(data_snr_cast%>%filter(dose%in%"300nM"),aes(x=protein_start,y=nmuts_unintended))+geom_point()+facet_wrap(~seqtech)

ggplot(data_snr_cast%>%filter(dose%in%"300nM"),aes(x=protein_start,y=coverage_mean_unintended))+geom_point()+facet_wrap(~seqtech)+scale_y_continuous(limits=c(0,200))

ggplot(data_snr_cast%>%filter(dose%in%"300nM"),aes(x=coverage_mean_unintended/depth_mean_unintended,fill=seqtech))+geom_density(alpha=.6)+scale_x_continuous("Allele fraction of unintended mutants",trans="log10")

ggplot(data_snr_cast%>%filter(dose%in%"300nM"),aes(x=coverage_mean_intended/depth_mean_intended,fill=seqtech))+geom_density(alpha=.6)+scale_x_continuous("Allele fraction of intended mutants",trans="log10")
# data_snr_cast=resmuts_adder(data_snr_cast)
# a=data%>%filter(seqtech%in%"sscs",dose%in%"300nM",is_intended%in%1,protein_start%in%c(245))


ggplot(data%>%filter(resmuts%in%T,dose%in%"300nM",is_intended%in%1),aes(x=species,y=ct_screen1_before,fill=seqtech))+geom_point(color="black",shape=21)+geom_line()+scale_y_continuous("Day 0 Coverage of Resistant Mutant",trans="log10")+cleanup+theme(axis.text.x=element_text(angle=90,hjust=.5,vjust=.5))

ggplot(data%>%filter(resmuts%in%T,dose%in%"300nM",is_intended%in%1),aes(x=species,y=ct_screen1_after,fill=seqtech))+geom_point(color="black",shape=21)+geom_line()+scale_y_continuous("Day 6 Coverage of Resistant Mutant",trans="log10")+cleanup+theme(axis.text.x=element_text(angle=90,hjust=.5,vjust=.5))

ggplot(data%>%filter(dose%in%"300nM"),aes(x=ct_screen1_before,))

ggplot(data%>%filter(is_intended%in%1,dose%in%"300nM"),aes(x=ct_screen1_before,color=seqtech))+stat_ecdf()+scale_x_continuous("Intended mutant coverage",trans="log10")+scale_y_continuous("CDF")

ggplot(data%>%filter(is_intended%in%1,dose%in%"300nM"),aes(x=ct_screen1_after,color=seqtech))+stat_ecdf()+scale_x_continuous("Intended mutant coverage",trans="log10")+scale_y_continuous("CDF")


ggplot(data%>%filter(dose%in%"300nM"),aes(x=ct_screen1_before,fill=seqtech))+geom_histogram()+facet_wrap(seqtech~is_intended)+scale_x_continuous(trans="log10")

ggplot(data%>%filter(is_intended%in%1,dose%in%"300nM",seqtech=="sscs"),aes(x=ct_screen1_before))+geom_histogram()+scale_x_continuous(trans="log10")

ggplot(data%>%filter(is_intended%in%1,dose%in%"300nM",seqtech=="sscs"),aes(x=ct_screen1_after))+geom_histogram()+scale_x_continuous(trans="log10")

ggplot(data%>%filter(dose%in%"300nM",is_intended%in%1),aes(x=ct_screen1_after,fill=seqtech))+geom_histogram()+facet_wrap(~seqtech)+scale_x_continuous(trans="log10")


# Next steps: try to fit the poisson model and the negative binomial model to the count distributions. See if the confidence intervals of the negative binomial distributions are bigger for the SSCS data.
ggplot(data%>%filter(is_intended%in%1,dose%in%"300nM",seqtech=="sscs"),aes(x=ct_screen1_before))+geom_histogram()+scale_x_continuous(limits=c(0,500))

a=data_snr_cast%>%filter(dose%in%"300nM")

```
SSCS data
Fitting negative binomial and poissons to data
```{r}
sscsdata=data%>%filter(is_intended%in%1,dose%in%"300nM",seqtech=="sscs")
sscsdata=sscsdata%>%filter(ct_screen1_before<=5000)
sum(sscsdata$ct_screen1_before)
nb_fit=glm.nb(sscsdata$ct_screen1_before~1)
summary(nb_fit)

# Extract parameter estimates fir begatuve binomial
nb_mu <- mean(sscsdata$ct_screen1_before)
nb_size <- nb_fit$theta  # Dispersion parameter

# Fit a Poisson model (mean only)
poisson_mu <- mean(sscsdata$ct_screen1_before)


# Generate a range of counts for plotting
count_range <- 1:5000

# Calculate negative binomial probabilities for the range
nb_probs <- dnbinom(count_range, size = nb_size, mu = nb_mu)

# Calculate probabilities for Poisson
poisson_probs <- dpois(count_range, lambda = poisson_mu)

# plot(count_range, nb_probs, type = "b", col = "red", lwd = 2)

# Create data frames for the fits
fit_df <- data.frame(
  count = rep(count_range, 2),
  density = c(nb_probs, poisson_probs),
  distribution = rep(c("Negative Binomial", "Poisson"), each = length(count_range))
)


ggplot(sscsdata)+
  geom_histogram(color="black",fill="gray90",aes(x=ct_screen1_before,y=..density..))+
  # geom_line(color="red",data=fit_df,aes(x=count,y=density))+
  # Negative binomial fit
  geom_line(
    data = fit_df[fit_df$distribution == "Negative Binomial", ],
    aes(x = count, y = density, color = distribution), size = 1
  ) +
  # Poisson fit
  geom_line(
    data = fit_df[fit_df$distribution == "Poisson", ], 
    aes(x = count, y = density, color = distribution), size = 1, linetype = "dashed"
  ) +
  # scale_y_continuous(trans="log10")+
  scale_x_continuous("SSCS Mutant coverage",limits=c(1,1000))
  

```

Tileseq data
Fitting negative binomial and poissons to data
```{r}
sscsdata=data%>%filter(is_intended%in%1,dose%in%"300nM",seqtech=="tileseq")
sscsdata=sscsdata%>%filter(ct_screen1_before<=10000)
sum(sscsdata$ct_screen1_before)
nb_fit=glm.nb(sscsdata$ct_screen1_before~1)
summary(nb_fit)

# Extract parameter estimates fir begatuve binomial
nb_mu <- mean(sscsdata$ct_screen1_before)
nb_size <- nb_fit$theta  # Dispersion parameter

# Fit a Poisson model (mean only)
poisson_mu <- mean(sscsdata$ct_screen1_before)


# Generate a range of counts for plotting
count_range <- 1:10000

# Calculate negative binomial probabilities for the range
nb_probs <- dnbinom(count_range, size = nb_size, mu = nb_mu)

# Calculate probabilities for Poisson
poisson_probs <- dpois(count_range, lambda = poisson_mu)

# plot(count_range, nb_probs, type = "b", col = "red", lwd = 2)

# Create data frames for the fits
fit_df <- data.frame(
  count = rep(count_range, 2),
  density = c(nb_probs, poisson_probs),
  distribution = rep(c("Negative Binomial", "Poisson"), each = length(count_range))
)


ggplot(sscsdata)+
  geom_histogram(color="black",fill="gray90",aes(x=ct_screen1_before,y=..density..))+
  # geom_line(color="red",data=fit_df,aes(x=count,y=density))+
  # Negative binomial fit
  geom_line(
    data = fit_df[fit_df$distribution == "Negative Binomial", ],
    aes(x = count, y = density, color = distribution), size = 1
  ) +
  # Poisson fit
  geom_line(
    data = fit_df[fit_df$distribution == "Poisson", ], 
    aes(x = count, y = density, color = distribution), size = 1, linetype = "dashed"
  ) +
  # scale_y_continuous(trans="log10")+
  scale_x_continuous("Tileseq Mutant coverage",limits=c(1,10000))+
  scale_y_continuous(limits=c(0,.001))
  

```
Doing an NGS, SSCS, DCS, and Tileseq comparison
This is lane 18b sample 
I had to discontinue because 
```{r}
dcs=read.csv("output/ABLEnrichmentScreens/ABL_Region1234_Tileseq/data/lane18b_data/DR_DCS_L18_10_8_ALL.csv",header = T,stringsAsFactors = F)
dcs$seqtech="dcs"
sscs=read.csv("output/ABLEnrichmentScreens/ABL_Region1234_Tileseq/data/lane18b_data/DR_SSCS_L18_10_8_ALL.csv",header = T,stringsAsFactors = F)
sscs$seqtech="sscs"
ngs=read.csv("output/ABLEnrichmentScreens/ABL_Region1234_Tileseq/data/lane18b_data/DR_NGS_L18_10_8_ALL.csv",header = T,stringsAsFactors = F)
ngs$seqtech="ngs"
tileseq=read.csv("output/ABLEnrichmentScreens/ABL_Region1234_Tileseq/data/lane18b_data/DR_TileSeq_BR1_A_H_ALL.csv",header = T,stringsAsFactors = F)
tileseq$seqtech="tileseq"
data=rbind(ngs,sscs,tileseq,dcs)

```





```{r}

```

